// SPDX-FileCopyrightText: 2021 Johannes Loher
//
// SPDX-License-Identifier: MIT

export const dvorak = {
  keycodeDisplayMapping: {
    BracketLeft: '/',
    BracketRight: '=',
    Comma: 'W',
    Equal: ']',
    IntlBackslash: '<',
    KeyA: 'A',
    KeyB: 'X',
    KeyC: 'J',
    KeyD: 'E',
    KeyE: '.',
    KeyF: 'U',
    KeyG: 'I',
    KeyH: 'D',
    KeyI: 'C',
    KeyJ: 'H',
    KeyK: 'T',
    KeyL: 'N',
    KeyM: 'M',
    KeyN: 'B',
    KeyO: 'R',
    KeyP: 'L',
    KeyQ: "'",
    KeyR: 'P',
    KeyS: 'O',
    KeyT: 'Y',
    KeyU: 'G',
    KeyV: 'K',
    KeyW: ',',
    KeyX: 'Q',
    KeyY: 'F',
    KeyZ: ';',
    Minus: '[',
    Period: 'V',
    Quote: '-',
    Semicolon: 'S',
    Slash: 'Z',
  },

  keybindingMapping: {
    BracketLeft: 'Minus',
    BracketRight: 'Equal',
    Comma: 'KeyW',
    Equal: 'BracketRight',
    KeyA: 'KeyA',
    KeyB: 'KeyN',
    KeyC: 'KeyI',
    KeyD: 'KeyH',
    KeyE: 'KeyD',
    KeyF: 'KeyY',
    KeyG: 'KeyU',
    KeyH: 'KeyJ',
    KeyI: 'KeyG',
    KeyJ: 'KeyC',
    KeyK: 'KeyV',
    KeyL: 'KeyP',
    KeyM: 'KeyM',
    KeyN: 'KeyL',
    KeyO: 'KeyS',
    KeyP: 'KeyR',
    KeyQ: 'KeyX',
    KeyR: 'KeyO',
    KeyS: 'Semicolon',
    KeyT: 'KeyK',
    KeyU: 'KeyF',
    KeyV: 'Period',
    KeyW: 'Comma',
    KeyX: 'KeyB',
    KeyY: 'KeyT',
    KeyZ: 'Slash',
    Minus: 'Quote',
    Period: 'KeyE',
    Quote: 'KeyQ',
    Semicolon: 'KeyZ',
    Slash: 'BracketLeft',
  },

  i18n: 'KEYBOARDLAYOUT.KeyboardLayoutDvorak',
};
